apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: nginx-server
    image: nginx:1.20
    ports:
    - containerPort: 80
  - name: afakharany
    image: afakharany/watcher:latest
